// <auto-generated />
namespace pokemon_challenge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PokemonInfoChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PokemonInfoChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201801201653375_PokemonInfoChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
